# Generated by Django 4.1.5 on 2023-01-13 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='neznáme mesto', max_length=100)),
                ('zipCode', models.CharField(default='## ###', max_length=5)),
                ('street', models.CharField(default='neznáma ulica', max_length=100)),
                ('streetNumber', models.CharField(default='#', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyCode', models.CharField(default='nezmáma spoločnosť', max_length=100)),
                ('companyName', models.CharField(default='nezmáma spoločnosť', max_length=100)),
                ('companyDescription', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(default='+421##########', max_length=13)),
                ('email', models.CharField(default='###@email', max_length=100)),
                ('website', models.CharField(default='obchod nemá web', max_length=100)),
                ('iconPath', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('addressId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryText', models.TextField(default='neznámy spôsob dopravy')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryCompanyCode', models.CharField(default='Neznámy doparvca', max_length=100)),
                ('deliveryCompanyDescription', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(default='+421##########', max_length=13)),
                ('email', models.CharField(default='###@email', max_length=100)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('fullCompanyName', models.CharField(default='###', max_length=100)),
                ('iconPath', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('addressId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company')),
                ('courierId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_to_package', to='base.deliverycompany')),
                ('deliveryCompanyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.deliverycompany')),
            ],
        ),
        migrations.CreateModel(
            name='StageCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageDescription', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='neznáme meno', max_length=100)),
                ('surname', models.CharField(default='neznáme priezvisko', max_length=100)),
                ('phone', models.CharField(default='+421##########', max_length=13)),
                ('email', models.CharField(default='###@email', max_length=100)),
                ('isRegistered', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('addressId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastSeen', models.TextField(blank=True, null=True)),
                ('estTimeODelivery', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('packageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.package')),
                ('stageCurrentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stagecode')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='receiverUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.useraccount'),
        ),
        migrations.AddField(
            model_name='package',
            name='typeOfDelivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.deliverycode'),
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='neznáme meno', max_length=100)),
                ('surname', models.CharField(default='neznáme priezvisko', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('picturePath', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deliveryCompanyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.deliverycompany')),
            ],
        ),
    ]
