# Generated by Django 4.1.5 on 2023-01-13 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_package_esttimeofdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='estTimeODelivery',
        ),
        migrations.AddField(
            model_name='package',
            name='dateOfOrder',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stage',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stage',
            name='estTimeOfDelivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='estTimeOFDelivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
