# Generated by Django 4.1.5 on 2023-01-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_package_esttimeofdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='courierId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.courier'),
        ),
    ]
