# Generated by Django 4.1.5 on 2023-01-14 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_package_courierid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['companyCode', 'companyName']},
        ),
        migrations.AlterModelOptions(
            name='deliverycompany',
            options={'ordering': ['deliveryCompanyCode', 'fullCompanyName']},
        ),
        migrations.RenameField(
            model_name='package',
            old_name='companyID',
            new_name='companyId',
        ),
        migrations.AlterField(
            model_name='stage',
            name='packageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='base.package'),
        ),
    ]
