# Generated by Django 4.1.5 on 2023-02-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_useraccount_email_alter_useraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.ImageField(default='shop_default.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='courier',
            name='picture',
            field=models.ImageField(default='id_default', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='deliverycompany',
            name='icon',
            field=models.ImageField(default='deliveryCompany_default.svg', null=True, upload_to=''),
        ),
    ]
