# Generated by Django 4.1.6 on 2023-02-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_company_icon_courier_picture_deliverycompany_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dateDelivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
