# Generated by Django 4.1.6 on 2023-02-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_company_phone_alter_deliverycompany_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='+421##########', max_length=13),
        ),
        migrations.AlterField(
            model_name='deliverycompany',
            name='phone',
            field=models.CharField(default='+421##########', max_length=13),
        ),
    ]
